export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const CHANGE_TASK_COMPLETE = "CHANGE_TASK_COMPLETE";
export const CHANGE_TITLE = "CHANGE_TITLE";

export const ADD_INNER_LIST = "ADD_INNER_LIST";
export const ADD_INNER_TEXTAREA = "ADD_INNER_TEXTAREA";
export const EDIT_INNER_TASK = "EDIT_INNER_TASK";
export const CHANGE_DEADLINE_DATE = "CHANGE_DEADLINE_DATE";
