export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const CHANGE_TASK_COMPLETE = "CHANGE_TASK_COMPLETE";
export const CHANGE_TITLE = "CHANGE_TITLE";
export const CHANGE_DEADLINE_DATE = "CHANGE_DEADLINE_DATE";
export const CHANGE_ORDER = "CHANGE_ORDER";
