export const ADD_MICROLIST = "ADD_MICROLIST";
export const ADD_MICROTEXT = "ADD_MICROTEXT";
export const EDIT_MICROTASK = "EDIT_MICROTASK";
export const ADD_MICROLIST_HERE = "ADD_MICROLIST_HERE";
export const DELETE_MICROTASK = "DELETE_MICROTASK";
